### ISSUE TITLE
Not showing up on Themer plugin

### ISSUE THREAD

**Issue by enderprism** [Darkempire78/Aliucord-Dracula-Theme#2]
> If you're reporting an UI issue, make sure you take a screenshot that shows the actual bug.

**Comment by enderprism** [comment]
Themer fails to load the theme when it's downloaded.
Here's the error:
```
[Themer] Failed to load theme Dracula%20Theme.json
org.json.JSONException: Value <!DOCTYPE of type java.lang.String cannot be converted to JSONObject
  at org.json.JSON.typeMismatch(JSON.java, [Themer] Failed to load theme Dracula%20Theme.json:112)
  at org.json.JSONObject.<init>(JSONObject.java:169)
  at org.json.JSONObject.<init>(JSONObject.java:182)
  at dev.vendicated.aliucordplugs.themer.Theme.json(Theme.kt:45)
  at dev.vendicated.aliucordplugs.themer.Theme.<init>(Theme.kt:35)
  at dev.vendicated.aliucordplugs.themer.ThemeLoader.loadThemes(ThemeLoader.kt:159)
  at dev.vendicated.aliucordplugs.themer.PatchesKt.addDownloadButton$lambda-42$lambda-41$lambda-40$lambda-39$lambda-38(Patches.kt:397)
  at dev.vendicated.aliucordplugs.themer.PatchesKt.$r8$lambda$CUF6gKGS4Rch0kNdYcB892c4BOg(Unknown Source:0)
  at dev.vendicated.aliucordplugs.themer.PatchesKt$$ExternalSyntheticLambda1.run(Unknown Source:8)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
  at java.lang.Thread.run(Thread.java:923)
```
If the issue comes from Themer, I'll open an issue on their repo.

**Comment by enderprism** [comment]
Bug resolved, the theme is working again.
